"""empty message

Revision ID: 1e5e0907e6eb
Revises: ab1bc4e145d4
Create Date: 2019-07-16 19:34:12.610011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5e0907e6eb'
down_revision = 'ab1bc4e145d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('under30', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'under30')
    # ### end Alembic commands ###
