"""empty message

Revision ID: 705266d21d9d
Revises: 
Create Date: 2019-09-02 15:32:31.740854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705266d21d9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'ingredients',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('recipe', 'under30',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'under30',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('recipe', 'ingredients',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
